---
version: "3.7"

services:

  tasmota-tb:
    image: techblog/tasmota-tb
    container_name: tasmota-tb
    restart: always
    environment:
      - TB_SERVER_ADDRESS= #eg. http://localhost:8080 http://my-server.addrsss https://mytb.com
      - REPORT_INTERVAL= #In minutes
    volumes:
      - ./tasmota-tb/config:/app/config
