---
version: "3.7"

services:

  tasmota-thingsboard-bridge:
    image: techblog/tasmota-thingsboard-bridge
    container_name: tasmota-thingsboard-bridge
    restart: always
    environment:
      - TB_SERVER_ADDRESS= #eg. http://localhost:8080 http://my-server.addrsss https://mytb.com
      - REPORT_INTERVAL= #In minutes
    volumes:
      - ./tasmota-tb/config:/app/config
